In [73]:

#load necessary libraries
import numpy as np
from scipy.stats import multivariate_normal #will use in q3 for evaluating our function


# **1)** Basic Exercises Using Numpy
Consider the vector 


$$
u = (1,2,3,3,2,1)^{T}
$$

**a)** Compute $U = I - \frac{2}{u^{T}u}uu^T$


In [3]:
u = np.array([1,2,3,3,2,1]).T #initialize vector 'u'
print(u)

[1 2 3 3 2 1]


In [4]:
matrixU = np.identity(u.shape[0]) - (2/np.matmul(np.transpose(u),u))*np.outer(u,np.transpose(u)) # create the matrix 'U'
print(matrixU)

[[ 0.92857143 -0.14285714 -0.21428571 -0.21428571 -0.14285714 -0.07142857]
 [-0.14285714  0.71428571 -0.42857143 -0.42857143 -0.28571429 -0.14285714]
 [-0.21428571 -0.42857143  0.35714286 -0.64285714 -0.42857143 -0.21428571]
 [-0.21428571 -0.42857143 -0.64285714  0.35714286 -0.42857143 -0.21428571]
 [-0.14285714 -0.28571429 -0.42857143 -0.42857143  0.71428571 -0.14285714]
 [-0.07142857 -0.14285714 -0.21428571 -0.21428571 -0.14285714  0.92857143]]


**b)** Let $C = UU$. Find the largest and smallest off diagonal elements of $C$.

In [5]:
matrixC = matrixU @ matrixU #define the matrix C

#find the largest and smallest off-diagonal elements of C- combine upper and lower triangle and find max and min

upper_tri = np.ravel(matrixC[np.triu_indices(6,k=1)])
lower_tri = np.ravel(matrixC[np.tril_indices(6,k=-1)])
lower_upper_tri = np.concatenate([upper_tri,lower_tri]) #combine the lower and upper triangles from matrix C

#get the max and min from the combined matrix lower_upper_tri which should contain the off-diagonal elements of C

print(matrixC)
#print results
print("The Maximum off-diagonal element of Matrix C is: ", max(lower_upper_tri),
"\n The Minimum off-diagonal element of Matrix C is: ", min(lower_upper_tri))


[[ 1.00000000e+00 -3.29597460e-17 -3.98986399e-17 -5.37764278e-17
  -3.98986399e-17 -2.77555756e-17]
 [-3.29597460e-17  1.00000000e+00 -7.97972799e-17 -1.07552856e-16
  -5.20417043e-17 -2.77555756e-17]
 [-3.98986399e-17 -7.97972799e-17  1.00000000e+00 -5.55111512e-17
  -9.36750677e-17 -5.55111512e-17]
 [-5.37764278e-17 -1.07552856e-16 -5.55111512e-17  1.00000000e+00
  -1.49186219e-16 -8.32667268e-17]
 [-3.98986399e-17 -5.20417043e-17 -9.36750677e-17 -1.49186219e-16
   1.00000000e+00 -2.77555756e-17]
 [-2.77555756e-17 -2.77555756e-17 -5.55111512e-17 -8.32667268e-17
  -2.77555756e-17  1.00000000e+00]]
The Maximum off-diagonal element of Matrix C is:  -2.7755575615628914e-17 
 The Minimum off-diagonal element of Matrix C is:  -1.491862189340054e-16


**c)** Find the largest and smallest diagonal elements of $C$.

In [6]:
#first extract them and store them:
diagonals = np.diag(matrixC)
print(max(diagonals))
print(min(diagonals))
#note the max and min values of the diagonal of Matrix C are equivalent

1.0
1.0


**d)** Compute $Uu$.

In [7]:
#compute matrix U times vector u
U_u = matrixU @ u
print(U_u)

[-1. -2. -3. -3. -2. -1.]


**e)** Compute the scalar $max_i$ $\sum_{j}|U_{ij}|$

In [8]:
row_sums = np.sum(np.abs(matrixU), axis=0)
print("The Maximum value of all the row sums: ", max(row_sums))

The Maximum value of all the row sums:  2.2857142857142856


**f)** Print the third row of $U$.

In [9]:
#print the third row of matrix U
print(matrixU[2])

[-0.21428571 -0.42857143  0.35714286 -0.64285714 -0.42857143 -0.21428571]


**g)** Print the elements of the second column below the diagonal.

In [10]:
#print the elements of the second column below the diagonal
#first get the lower triangle indices
lower_diag_U = matrixU[:,1][2:]
#then just print column 2
print(lower_diag_U.T)


[-0.42857143 -0.42857143 -0.28571429 -0.14285714]


**h)** Let $A$ be the first three columns of $U$. Compute $P = AA^T$.

In [11]:
#define matrix A as first three columns of matrix U
matrixA = matrixU[:,0:3]
#compute P by multiplying A by its transpose
matrixP = np.matmul(matrixA,np.transpose(matrixA))
print(matrixP)

[[ 9.28571429e-01 -1.42857143e-01 -2.14285714e-01 -2.77555756e-17
  -2.77555756e-17 -1.38777878e-17]
 [-1.42857143e-01  7.14285714e-01 -4.28571429e-01 -5.55111512e-17
  -2.77555756e-17 -1.38777878e-17]
 [-2.14285714e-01 -4.28571429e-01  3.57142857e-01 -2.77555756e-17
  -5.55111512e-17 -2.77555756e-17]
 [-2.77555756e-17 -5.55111512e-17 -2.77555756e-17  6.42857143e-01
   4.28571429e-01  2.14285714e-01]
 [-2.77555756e-17 -2.77555756e-17 -5.55111512e-17  4.28571429e-01
   2.85714286e-01  1.42857143e-01]
 [-1.38777878e-17 -1.38777878e-17 -2.77555756e-17  2.14285714e-01
   1.42857143e-01  7.14285714e-02]]


**i)** Show that $P$ is idempotent by recomputing (e) with $PP - P$.

In [12]:
#show matrix P is idempotent by showing P is returned after computing PP - P:
returnedMatrix = np.matmul(matrixP,matrixP) - matrixP #This is PP - P
row_sum = np.sum(np.abs(returnedMatrix),axis = 0) #calculate the row sums of the returned matrix

print("After re-calculating e, the following row sum is obtained: ", np.max(row_sum))

After re-calculating e, the following row sum is obtained:  2.2997476938663954e-16


Since $PP - P$ is about $0$, it is evident that $P$ is an idempotent matrix.

**j)** Let $B$ be the last three columns of $U$. Compute $Q = BB^{T}$.

In [13]:
matrixB = matrixU[:,-3:] #create matrix B
matrixQ = matrixB @ matrixB.T
print("Matrix Q: \n ", matrixQ)

Matrix Q: 
  [[ 7.14285714e-02  1.42857143e-01  2.14285714e-01 -2.60208521e-17
  -1.21430643e-17 -1.38777878e-17]
 [ 1.42857143e-01  2.85714286e-01  4.28571429e-01 -5.20417043e-17
  -2.42861287e-17 -2.77555756e-17]
 [ 2.14285714e-01  4.28571429e-01  6.42857143e-01 -2.77555756e-17
  -3.81639165e-17 -2.77555756e-17]
 [-2.60208521e-17 -5.20417043e-17 -2.77555756e-17  3.57142857e-01
  -4.28571429e-01 -2.14285714e-01]
 [-1.21430643e-17 -2.42861287e-17 -3.81639165e-17 -4.28571429e-01
   7.14285714e-01 -1.42857143e-01]
 [-1.38777878e-17 -2.77555756e-17 -2.77555756e-17 -2.14285714e-01
  -1.42857143e-01  9.28571429e-01]]


**k)** Show that $Q$ is idempotent by recomputing e) with $QQ - Q$

In [14]:
idempotentQ = matrixQ @ matrixQ - matrixQ #calculate QQ - Q

row_sum2= np.sum(np.abs(idempotentQ),axis = 0) #do the same calculation from e)

print("After re-calculating e for the matrix QQ - Q, the following row sum is obtained: ", np.max(row_sum2))

After re-calculating e for the matrix QQ - Q, the following row sum is obtained:  2.2997476938663954e-16


Because all elements in  $QQ - Q$ are about 0, we can say that $Q$ is an idempotent matrix.

**l)** Compute $P + Q$

In [15]:
print(matrixP + matrixQ)

[[ 1.00000000e+00 -2.77555756e-17 -5.55111512e-17 -5.37764278e-17
  -3.98986399e-17 -2.77555756e-17]
 [-2.77555756e-17  1.00000000e+00 -1.11022302e-16 -1.07552856e-16
  -5.20417043e-17 -4.16333634e-17]
 [-5.55111512e-17 -1.11022302e-16  1.00000000e+00 -5.55111512e-17
  -9.36750677e-17 -5.55111512e-17]
 [-5.37764278e-17 -1.07552856e-16 -5.55111512e-17  1.00000000e+00
  -1.66533454e-16 -5.55111512e-17]
 [-3.98986399e-17 -5.20417043e-17 -9.36750677e-17 -1.66533454e-16
   1.00000000e+00 -2.77555756e-17]
 [-2.77555756e-17 -4.16333634e-17 -5.55111512e-17 -5.55111512e-17
  -2.77555756e-17  1.00000000e+00]]


# 2) Compute the correlation between number of failures and temperature at launch, deleting the last, missing observation (the disaster)

In [16]:
#import pandas
import pandas as pd
#read in data
oringp_data = pd.read_csv("/Users/collinkennedy/Dropbox/UC Davis/Grad/spring_quarter_2022/STA208-Machine_Learning/hw0/oringp.dat",
header= None,engine='python',delimiter='\s+') #reading in the data
oringp_data.columns = ('flight_number','date','no_o_rings','number_failed','temperature') #renaming the columns
oringp_data.head() #viewing the first 5 observations of the data

oringp_data = oringp_data.dropna() #drop the last observation 

print(oringp_data)

   flight_number      date  no_o_rings  number_failed  temperature
0              1   4/12/81           6            0.0           66
1              2  11/12/81           6            1.0           70
2              3   3/22/82           6            0.0           69
3              5  11/11/82           6            0.0           68
4              6   4/04/83           6            0.0           67
5              7   6/18/83           6            0.0           72
6              8   8/30/83           6            0.0           73
7              9  11/28/83           6            0.0           70
8           41-B   2/03/84           6            1.0           57
9           41-C   4/06/84           6            1.0           63
10          41-D   8/30/84           6            1.0           70
11          41-G  10/05/84           6            0.0           78
12          51-A  11/08/84           6            0.0           67
13          51-C   1/24/85           6            3.0         

In [17]:
len(oringp_data['flight_number'])
np.log(10)
np.array([[1,2][3,4]])

TypeError: list indices must be integers or slices, not tuple

In [ ]:
np.corrcoef(oringp_data['number_failed'],oringp_data['temperature'])

array([[ 1.        , -0.56132843],
       [-0.56132843,  1.        ]])

$Corr(number\_failed, temperature ) = -.56$

# 3)

In [56]:
import math #will need this to exponentiate log-likelihood function
#create function
def dmvnorm_lowrank(y,mu,Z,sigma0,sigma1,log = False):
    #create a matrix by y - u called y_u
    y_u = y - mu.reshape(len(y),1)

    #another matrix to make the code below more concise
    sigma_Z = (sigma1**2)*(Z @ Z.T) + (sigma0**2)*np.identity(len(y))

    #log density function:
    log_density_function =( (-len(y)/2)*np.log(2*np.pi) - .5*np.log(np.linalg.det(sigma_Z)) - 
       .5*np.matmul(y_u.T,np.linalg.inv(sigma_Z)) @ y_u )

    if log == False: ##when log = FALSE, function should calculate the log likelihood
       log_likelihood = log_density_function #rename the log density function in this case since we are evaluating it at y
       return(log_likelihood)

    else: # when log = True, function should calculate the original likelihood function
       likelihood = np.exp(log_density_function)
       return(likelihood)

        


To test the function, we consider the following constraints and random variables:
 - n = 100, q = 5
 - $\sigma_0 $ -> random number between 0 and 100
 - $\sigma_1 $ -> random number between 0 and 100
 - $\mu \sim Uniform(0,10)$
 - $Z \sim N(10,2)$
 - $y \sim N(\mu, \sigma^{2}_{1}ZZ^{T} + \sigma^{2}_{0}I_n)$


In [59]:
#simulate the data and test the function
np.random.seed(1)
sigma0 = np.random.randint(100)
sigma1 = np.random.randint(100)
mu = np.random.uniform(0,10,100)

#create the Z matrix
Z = np.random.normal(10,2,500).reshape(100,5) #reshape into a 100 x 5 matrix

#draw 100 samples for y from the multivariate normal distribution
y = np.random.multivariate_normal(mu, sigma1**2 * np.identity(100) + sigma0**2 * Z @ Z.T, 1).reshape(100,1) #again, 
print(y)


[[ 454.99928065]
 [ 327.64959978]
 [  76.35365904]
 [ 327.84960059]
 [ 212.22293983]
 [  94.0688189 ]
 [ 609.57556012]
 [ -12.44265446]
 [ 467.22262725]
 [   9.89314634]
 [ 271.10328119]
 [ 187.83330477]
 [ 368.20098208]
 [  26.51600309]
 [ 405.42104685]
 [ 607.792463  ]
 [ 145.06882152]
 [ 198.01038752]
 [ 456.43077917]
 [ 145.03278894]
 [ 338.11353432]
 [ 125.86613561]
 [ 301.91611244]
 [ 167.6945685 ]
 [ -49.18959979]
 [ 426.11175796]
 [ 133.01017959]
 [ -48.93039453]
 [ 357.89941457]
 [ 178.62360352]
 [ 381.794498  ]
 [ 133.95949885]
 [ 429.45309831]
 [-324.04032173]
 [ 408.93681929]
 [ 322.609948  ]
 [ 149.09747957]
 [ 122.70052791]
 [ 714.88063187]
 [ -74.30446704]
 [ 165.80977818]
 [  31.09733462]
 [ 616.08814362]
 [ 642.94824555]
 [ 292.89838324]
 [ 266.59790884]
 [ 424.37808313]
 [ 296.79029977]
 [ 360.06636789]
 [ 386.46108421]
 [ 414.15067361]
 [ 379.81306572]
 [ 472.26227081]
 [ 263.05293799]
 [ 266.82769349]
 [ 213.19156777]
 [ 525.24321179]
 [ 440.46644655]
 [ 560.0358067

In [25]:
mu.shape

(100,)

In [60]:
# Calculating the likelihood for the above generated data 

#a. Log Likelihood 
log_likelihood = dmvnorm_lowrank(y,mu,Z,sigma0,sigma1,log = False)

#b. Normal Likelihood
print(log_likelihood)

ll = dmvnorm_lowrank(y,mu,Z,sigma0,sigma1,log = True)
print(ll)


[[-inf]]
[[0.]]


/Users/collinkennedy/opt/anaconda3/lib/python3.7/site-packages/numpy/linalg/linalg.py:2125: RuntimeWarning: overflow encountered in det
  r = _umath_linalg.det(a, signature=signature)


In [78]:
#Lets try n  = 10, q = 4
#simulate the data and test the function
n = 10
q = 10
np.random.seed(1)
sigma0 = np.random.randint(10) #sigma0 is a single value between 0 and 100
sigma1 = np.random.randint(10) #sigma1 is a single value between 0 and 100
mu = np.random.uniform(0,10,n) #last parameter is n





#create the Z matrix
Z = np.random.uniform(size=(n,q)) #randomly sampled n x q matrix

#create covariance matrix for testing later
cov_matrix = (sigma1**2) * np.matmul(Z,Z.T) + sigma0**2 * np.identity(n)

#draw 10 samples for y from the multivariate normal distribution
y = np.random.multivariate_normal(mu, sigma1**2 * np.identity(10) + sigma0**2 * Z @ Z.T, 1).reshape(10,1) #again, 

# Calculating the likelihood for the above generated data 

#a. Log Likelihood 
log_likelihood = dmvnorm_lowrank(y,mu,Z,sigma0,sigma1,log = False)

#b.  Likelihood
ll = dmvnorm_lowrank(y,mu,Z,sigma0,sigma1,log = True)


#Obtaining results using scipy functions for later comparison
log_likelihood_scipy = multivariate_normal.logpdf(y, mean= mu, cov= cov_matrix )
likelihood_scipy = multivariate_normal.pdf(y, mean = mu, cov=cov_matrix)


#Verifying Results using Scipy
#first log-likelihood
print("log likelihood using dvnorm_lowrank: ", log_likelihood[0] )
print("log likelihood using scipy's logpdf function: ", log_likelihood_scipy )

#likelihood
print("likelihood using dvnorm_lowrank: ", ll[0])
print("likelihood using scipy's pdf function: ", likelihood_scipy)



log likelihood using dvnorm_lowrank:  [-35.08201162]
log likelihood using scipy's logpdf function:  [-32.02460594 -32.05220027 -32.17118195 -32.0962549  -32.09458891
 -31.99091614 -32.19726673 -32.14907253 -32.02338298 -32.44905457]
likelihood using dvnorm_lowrank:  [5.80865979e-16]
likelihood using scipy's pdf function:  [1.23563544e-14 1.20200505e-14 1.06716900e-14 1.15020065e-14
 1.15211847e-14 1.27797291e-14 1.03969206e-14 1.09102626e-14
 1.23714750e-14 8.08266644e-15]


In [79]:
print(Z)

[[0.20445225 0.87811744 0.02738759 0.67046751 0.4173048  0.55868983
  0.14038694 0.19810149 0.80074457 0.96826158]
 [0.31342418 0.69232262 0.87638915 0.89460666 0.08504421 0.03905478
  0.16983042 0.8781425  0.09834683 0.42110763]
 [0.95788953 0.53316528 0.69187711 0.31551563 0.68650093 0.83462567
  0.01828828 0.75014431 0.98886109 0.74816565]
 [0.28044399 0.78927933 0.10322601 0.44789353 0.9085955  0.29361415
  0.28777534 0.13002857 0.01936696 0.67883553]
 [0.21162812 0.26554666 0.49157316 0.05336255 0.57411761 0.14672857
  0.58930554 0.69975836 0.10233443 0.41405599]
 [0.69440016 0.41417927 0.04995346 0.53589641 0.66379465 0.51488911
  0.94459476 0.58655504 0.90340192 0.1374747 ]
 [0.13927635 0.80739129 0.39767684 0.1653542  0.92750858 0.34776586
  0.7508121  0.72599799 0.88330609 0.62367221]
 [0.75094243 0.34889834 0.26992789 0.89588622 0.42809119 0.96484005
  0.6634415  0.62169572 0.11474597 0.94948926]
 [0.44991213 0.57838961 0.4081368  0.23702698 0.90337952 0.57367949
  0.00287033